Minor housekeeping.
lcov comments, test coverage, minor edits.

diff --git a/tests/common b/tests/common
--- a/tests/common
+++ b/tests/common
@@ -28,6 +28,15 @@ checkrv () {
     fi
 }
 
+checkerr () {
+    if [ "$1" != "1" ]; then
+        echo "FAIL ${DESC}"
+        exit 1
+    else
+        echo "OK ${DESC}"
+    fi
+}
+
 tdone () {
     rm -f report nreport
 }
