Support running individual test file(s) instead of whole suite.

diff --git a/tests/common b/tests/common
--- a/tests/common
+++ b/tests/common
@@ -1,12 +1,30 @@
+#
+#  Copyright 2014-2015 Jyri J. Virkki <jyri@virkki.com>
+#
+#  This file is part of dupd.
+#
+#  dupd is free software: you can redistribute it and/or modify it
+#  under the terms of the GNU General Public License as published by
+#  the Free Software Foundation, either version 3 of the License, or
+#  (at your option) any later version.
+#
+#  dupd is distributed in the hope that it will be useful, but
+#  WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+#  General Public License for more details.
+#
+#  You should have received a copy of the GNU General Public License
+#  along with dupd.  If not, see <http://www.gnu.org/licenses/>.
+#
 
 rm -f report nreport
 
 checkrv () {
     if [ "$1" != "0" ]; then
-	echo "FAIL ${DESC}"
-	exit 1
+        echo "FAIL ${DESC}"
+        exit 1
     else
-	echo "OK ${DESC}"
+        echo "OK ${DESC}"
     fi
 }
 
